version: "3"

services:
    nginx:
      image: nginx 
      ports:
        - "2297:80"
      volumes:
        - ./nginx/default.config:/etc/nginx/conf.d/default.conf:ro
    node-server:
      build: . 
      ports:
        - "3000:3000" 


